# Generated by Django 3.1.10 on 2021-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.CharField(max_length=1)),
                ('to_node', models.CharField(max_length=1)),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
